POST http://localhost:3000/messages
Content-Type: application/json

{
  "messages": [
    { "message": "hello" },
    { "message": "good morning!" },
    { "message": "good afternoon!" },
    { "message": "good evening!" },
    { "message": "good night!" }
  ]
}
